version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 40
    # Enable security updates
    allow:
      - dependency-type: "all"
    # Labels for easier filtering
    labels:
      - "dependencies"
